Controllers/OrderController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Sky.Areas.Identity.Data;
using Sky.Data;
using Sky.Models;
using static Sky.Data.Helper;

namespace Sky.Controllers
{
    public class OrderController : Controller
    {
        private readonly SkyAppDbContext _context;
        private readonly UserManager<SkyUser> _userManager;

        public OrderController(SkyAppDbContext context,
            UserManager<SkyUser> userManager)
        {
            _context = context;
            _userManager = userManager;
        }

        private string StatusMessage { set; get; }

        [Authorize]
        // GET: Order
        public async Task<IActionResult> Index(string searchString, string status)
        {
            ViewData["CurrentFilter"] = searchString;
            ViewData["Status"] = status;

            var iduser = _userManager.GetUserId(User);
            try
            {
                var skyAppDbContext = _context.OrderDbSet.Where(c => c.UserId == iduser);

                if (!String.IsNullOrEmpty(searchString))
                {
                    skyAppDbContext = skyAppDbContext.Where(s => s.OrderTextId.Contains(searchString));
                }



                switch (status)
                {
                    case "dang-cho":
                        skyAppDbContext = skyAppDbContext.Where(s => s.OrderStatus.Contains("Đang chờ duyệt"));
                        break;
                    case "da-xac-nhan":
                        skyAppDbContext = skyAppDbContext.Where(s => s.OrderStatus.Contains("Đã xác nhận"));
                        break;
                    case "dang-giao":
                        skyAppDbContext = skyAppDbContext.Where(s => s.OrderStatus.Contains("Đang giao"));
                        break;
                    case "da-giao":
                        skyAppDbContext = skyAppDbContext.Where(s => s.OrderStatus.Contains("Đã giao"));
                        break;
                    case "da-huy":
                        skyAppDbContext = skyAppDbContext.Where(s => s.OrderStatus.Contains("Đã hủy"));
                        break;
                    default:
                        skyAppDbContext = skyAppDbContext.OrderByDescending(s => s.OrderDate);
                        break;
                }

                if (!skyAppDbContext.Any())
                {
                    ViewData["Mess"] = "Không có đơn hàng hợp lệ!";
                }

                //Lấy hình ảnh thum của từng đơn hàng
                List<string> listimg = new List<string>();

                foreach (var i in skyAppDbContext.ToList())
                {

                    var order_de = _context.OrderDetailDbSet.Where(c => c.OrderId == i.OrderId).ToList().FirstOrDefault();

                    var product = _context.ProductDbSet.Find(order_de.ProductId);

                    listimg.Add(product.ProductImage);
                }

                ViewBag.ListImg = listimg;

                return View(await skyAppDbContext.ToListAsync());
            }
            catch
            {
                ViewData["Mess"] = "Đã có lỗi!";
            }
            return View();
        }

        [Authorize(Roles = "Admin, Manager")]
        public async Task<IActionResult> Manage(string searchString, string status)
        {
            ViewData["CurrentFilter"] = searchString;
            ViewData["Status"] = status;

            try
            {
                var skyAppDbContext = _context.OrderDbSet.Select(a => a);

                if (!String.IsNullOrEmpty(searchString))
                {
                    skyAppDbContext = skyAppDbContext.Where(s => s.OrderTextId.Contains(searchString));
                }



                switch (status)
                {
                    case "dang-cho":
                        skyAppDbContext = skyAppDbContext.Where(s => s.OrderStatus.Contains("Đang chờ duyệt"));
                        break;
                    case "da-xac-nhan":
                        skyAppDbContext = skyAppDbContext.Where(s => s.OrderStatus.Contains("Đã xác nhận"));
                        break;
                    case "dang-giao":
                        skyAppDbContext = skyAppDbContext.Where(s => s.OrderStatus.Contains("Đang giao"));
                        break;
                    case "da-giao":
                        skyAppDbContext = skyAppDbContext.Where(s => s.OrderStatus.Contains("Đã giao"));
                        break;
                    case "da-huy":
                        skyAppDbContext = skyAppDbContext.Where(s => s.OrderStatus.Contains("Đã hủy"));
                        break;
                    default:
                        skyAppDbContext = skyAppDbContext.OrderByDescending(s => s.OrderDate);
                        break;
                }

                if (!skyAppDbContext.Any())
                {
                    ViewData["Mess"] = "Không có đơn hàng hợp lệ!";
                }

                //Lấy hình ảnh thum của từng đơn hàng
                List<string> listimg = new List<string>();

                foreach (var i in skyAppDbContext.ToList())
                {

                    var order_de = _context.OrderDetailDbSet.Where(c => c.OrderId == i.OrderId).ToList().FirstOrDefault();

                    var product = _context.ProductDbSet.Find(order_de.ProductId);

                    listimg.Add(product.ProductImage);
                }

                ViewBag.ListImg = listimg;

                return View(await skyAppDbContext.ToListAsync());
            }
            catch
            {
                ViewData["Mess"] = "Đã có lỗi!";
            }
            return View();
        }

        [NoDirectAccess]
        [Authorize]
        public async Task<IActionResult> AcceptOrder(string searchString)
        {
            ViewData["CurrentFilter"] = searchString;

            var skyAppDbContext = _context.OrderDbSet.Select(a => a).Where(c => c.OrderStatus == "Đang chờ duyệt");

            if (!String.IsNullOrEmpty(searchString))
            {
                skyAppDbContext = skyAppDbContext.Where(s => s.OrderTextId.Contains(searchString));
            }

            if (!skyAppDbContext.Any())
            {
                ViewData["Mess"] = "Không có đơn hàng hợp lệ!";
            }

            skyAppDbContext = skyAppDbContext.OrderByDescending(c => c.OrderDate);

            return View(await skyAppDbContext.ToListAsync());
        }

        [NoDirectAccess]
        [Authorize]
        public IActionResult AcceptOrderConfirmed(int id)
        {
            var skyAppDbContext = _context.OrderDbSet.Where(c => c.OrderId == id).FirstOrDefault();

            skyAppDbContext.OrderStatus = "Đã xác nhận";
            skyAppDbContext.OrderLock = true;

            _context.SaveChanges();

            return RedirectToAction(nameof(AcceptOrder));
        }

        [NoDirectAccess]
        [Authorize]
        public IActionResult DeleteOrderCancel()
        {
            var skyAppDbContext = _context.OrderDbSet.Where(c => c.OrderStatus == "Đã hủy").ToList();

            return View(skyAppDbContext);
        }

        //Hủy đơn hàng
        [Authorize]
        [NoDirectAccess]
        public IActionResult CancelOrder(int id)
        {
            var iduser = _userManager.GetUserId(User);

            var skyAppDbContext = _context.OrderDbSet.Where(c => c.UserId == iduser && c.OrderId == id).FirstOrDefault();

            ViewData["Mess"] = "Bạn có muốn hủy đơn hàng " + skyAppDbContext.OrderTextId + " không?";

            ViewBag.Id = id;

            return View();
        }

        [Authorize]
        [NoDirectAccess]
        public IActionResult CancelOrderConfirmed(int id)
        {
            try
            {
                var iduser = _userManager.GetUserId(User);

                var skyAppDbContext = _context.OrderDbSet.Where(c => c.UserId == iduser && c.OrderId == id).FirstOrDefault();

                skyAppDbContext.OrderStatus = "Đã hủy";

                _context.SaveChanges();

                ViewData["Mess"] = "Hủy thành công";
            }
            catch
            {
                ViewData["Mess"] = "Hủy không thành công";
            }

            return RedirectToAction("Index");
        }

        [NoDirectAccess]
        [Authorize]
        //Waiting success
        public IActionResult Success()
        {
            ViewBag.text = HttpContext.Session.GetString("Status");

            //ViewBag.text = StatusMessage;

            return View();
        }
        [Authorize]
        [NoDirectAccess]
        public async Task<IActionResult> DeleteOrderCancelConfirmed(int id)
        {
            var order = await _context.OrderDbSet.FindAsync(id);
            _context.OrderDbSet.Remove(order);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(DeleteOrderCancel));
        }
        public async Task<IActionResult> DeleteAllOrderCancel()
        {
            var order = await _context.OrderDbSet.Where(c => c.OrderStatus == "Đã hủy").ToListAsync();

            foreach (var item in order){
                _context.OrderDbSet.Remove(item);
            }
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(DeleteOrderCancel));
        }

        [Authorize]
        [NoDirectAccess]
        // GET: Order/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var order = await _context.OrderDbSet
                .FirstOrDefaultAsync(m => m.OrderId == id);
            if (order == null)
            {

Controllers/OrderDetailController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Sky.Areas.Identity.Data;
using Sky.Data;
using Sky.Models;
using static Sky.Data.Helper;

namespace Sky.Controllers
{
    public class OrderDetailController : Controller
    {
        private readonly SkyAppDbContext _context;
        private readonly UserManager<SkyUser> _userManager;

        public OrderDetailController(SkyAppDbContext context,
            UserManager<SkyUser> userManager)
        {
            _context = context;
            _userManager = userManager;
        }

        [NoDirectAccess]
        public async Task<IActionResult> ChiTiet(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            try
            {
                var iduser = _userManager.GetUserId(User);

                var order = _context.OrderDbSet.Where(c => c.OrderId == id).ToList().FirstOrDefault();

                var orderDetail = await _context.OrderDetailDbSet
                    .Include(o => o.Order)
                    .Include(o => o.Product).Where(c => c.OrderId == id).ToListAsync();

                if (orderDetail == null)
                {
                    return NotFound();
                }

                ViewBag.orderIdText = order.OrderTextId;

                ViewBag.orderPrice = order.OrderPrice;

                ViewBag.order = order;

                return View(orderDetail);
            }
            catch
            {
                ViewBag.Mess = "Đã có lỗi";
            }

            return View();

        }

        /*
        [Authorize]
        // GET: OrderDetails
        public async Task<IActionResult> Index()
        {
            var id = _userManager.GetUserId(User);


            var skyAppDbContext = _context.OrderDetailDbSet.Include(o => o.Order).Include(o => o.Product);
            return View(await skyAppDbContext.ToListAsync());
        }

        // GET: OrderDetail/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var orderDetail = await _context.OrderDetailDbSet
                .Include(o => o.Order)
                .Include(o => o.Product)
                .FirstOrDefaultAsync(m => m.OrderId == id);
            if (orderDetail == null)
            {
                return NotFound();
            }

            return View(orderDetail);
        }

        // GET: OrderDetail/Create
        public IActionResult Create()
        {
            ViewData["OrderId"] = new SelectList(_context.OrderDbSet, "OrderId", "OrderNote");
            ViewData["ProductId"] = new SelectList(_context.ProductDbSet, "ProductId", "ProductDescription");
            return View();
        }

        // POST: OrderDetail/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("OrderId,ProductId,ProductOrderName,ProductOrderPrice,Quantity")] OrderDetail orderDetail)
        {
            if (ModelState.IsValid)
            {
                _context.Add(orderDetail);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["OrderId"] = new SelectList(_context.OrderDbSet, "OrderId", "OrderNote", orderDetail.OrderId);
            ViewData["ProductId"] = new SelectList(_context.ProductDbSet, "ProductId", "ProductDescription", orderDetail.ProductId);
            return View(orderDetail);
        }

        [NoDirectAccess]
        // GET: OrderDetail/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var orderDetail = await _context.OrderDetailDbSet.FindAsync(id);
            if (orderDetail == null)
            {
                return NotFound();
            }
            ViewData["OrderId"] = new SelectList(_context.OrderDbSet, "OrderId", "OrderNote", orderDetail.OrderId);
            ViewData["ProductId"] = new SelectList(_context.ProductDbSet, "ProductId", "ProductDescription", orderDetail.ProductId);
            return View(orderDetail);
        }

        // POST: OrderDetail/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("OrderId,ProductId,ProductOrderName,ProductOrderPrice,Quantity")] OrderDetail orderDetail)
        {
            if (id != orderDetail.OrderId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(orderDetail);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!OrderDetailExists(orderDetail.OrderId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["OrderId"] = new SelectList(_context.OrderDbSet, "OrderId", "OrderNote", orderDetail.OrderId);
            ViewData["ProductId"] = new SelectList(_context.ProductDbSet, "ProductId", "ProductDescription", orderDetail.ProductId);
            return View(orderDetail);
        }

        // GET: OrderDetail/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var orderDetail = await _context.OrderDetailDbSet
                .Include(o => o.Order)
                .Include(o => o.Product)
                .FirstOrDefaultAsync(m => m.OrderId == id);
            if (orderDetail == null)
            {
                return NotFound();
            }

            return View(orderDetail);
        }

        // POST: OrderDetail/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var orderDetail = await _context.OrderDetailDbSet.FindAsync(id);
            _context.OrderDetailDbSet.Remove(orderDetail);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }
        */

        private bool OrderDetailExists(int id)
        {
            return _context.OrderDetailDbSet.Any(e => e.OrderId == id);
        }
    }
}

Views/Order/AcceptOrder.cshtml
@model IEnumerable<Sky.Models.Order>
@using System.Globalization

@{
    ViewData["Title"] = "Duyệt đơn hàng mới";
    Layout = "~/Areas/Identity/Pages/Admin/_AdminLayout.cshtml";
    int i = 0;
    CultureInfo culture = CultureInfo.CreateSpecificCulture("vi-VI");
}

<h2 class="text-center mt-5 mb-4">
    <i class="fas fa-check-circle text-success fa-lg mr-2"></i>
    Duyệt đơn hàng mới
</h2>

<div class="card shadow mb-3">
    <div class="card-body d-flex py-2">
        <div class="flex-grow-1 d-inline-flex form-inline">
            <div class="form-group m-2">
                <a class="btn btn-success" asp-action="Manage">Xem tất cả</a>
            </div>
        </div>
        <div class="p-0">
            <form asp-action="AcceptOrder" method="get" class="form-inline ">
                <div class="form-group m-2">
                    <label class="input-group-prepend">Tìm kiếm </label>
                </div>
                <div class="form-group m-2">
                    <div class="input-group">
                        <input type="text" class="form-control" name="SearchString" value="@ViewData["CurrentFilter"]" />
                        <div class="input-group-append">
                            <button class="btn btn-primary" type="submit">
                                <i class="fas fa-search"></i>
                            </button>
                        </div>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>

<div class="card shadow">
    <div class="card-body">
        <div class="table-responsive">
            <table class="table dataTable" id="dataTable" width="100%" cellspacing="0">
                <thead>
                    <tr class="text-center">
                        <th>STT</th>
                        <th>
                            Mã đơn hàng
                        </th>
                        <th>

                        </th>
                        <th>
                            Tình trạng
                        </th>
                        <th>
                            Ngày đặt hàng
                        </th>
                        <th>
                            Tổng tiền
                        </th>
                        <th></th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var item in Model)
                    {
                        <tr class="text-center">
                            <td class="align-middle">
                                @(i+1)
                            </td>
                            <td class="align-middle">
                                <small>@Html.DisplayFor(modelItem => item.OrderTextId)</small>
                            </td>
                            <td class="align-middle">
                                @*<img src="@("~/image/" + ViewBag.ListImg[i])" asp-append-version="true" style="height:150px" class="rounded" />*@
                            </td>
                            <td class="align-middle">
                                @Html.DisplayFor(modelItem => item.OrderStatus)
                            </td>
                            <td class="align-middle">
                                @((item.OrderDate).ToString("dd/MM/yyyy HH:mm"))
                            </td>
                            <td class="align-middle">
                                <strong>@((item.OrderPrice).ToString("#,##0", culture))</strong>
                            </td>
                            <td class="align-middle">
                                <a onclick="showInPopup('@Url.Action("Edit", "Order", new { id = item.OrderId}, Context.Request.Scheme)', 'Edit Order')"
                                   class="btn btn-sm btn-primary text-white">Sửa</a>
                                <a onclick="showInPopup('@Url.Action("Details", "Order", new { id = item.OrderId}, Context.Request.Scheme)', 'Detail Order')"
                                   class="btn btn-sm btn-success text-white">Xem</a>
                                <a onclick="showInPopup('@Url.Action("Delete", "Order", new { id = item.OrderId}, Context.Request.Scheme)', 'Delete Order')"
                                   class="btn btn-sm btn-danger text-white">Xóa</a>
                                <a onclick="showInPopup('@Url.Action("ChiTiet", "OrderDetail", new { id = item.OrderId}, Context.Request.Scheme)', 'ChiTiet Order')"
                                   class="btn btn-sm btn-info text-white">Chi Tiết</a>
                                <a asp-action="AcceptOrderConfirmed" asp-route-id="@item.OrderId"
                                   class="btn btn-sm btn-secondary text-white">Duyệt</a>
                            </td>
                        </tr>
                        i++;
                    }
                </tbody>
            </table>
        </div>
    </div>
</div>



<div class="modal" tabindex="-1" role="dialog" id="form-modal">
    <div class="modal-dialog modal-lg" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title"></h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">×</span>
                </button>
            </div>
            <div class="modal-body">

            </div>
        </div>
    </div>
</div>


<p class="h4 my-5 text-center">
    @ViewData["Mess"]
</p>

@section Scripts{
    <script>
        $(document).ready(function () {
            $('#dataTable').DataTable({
                "language": {
                    "lengthMenu": "Hiển thị _MENU_ kết quả mỗi trang",
                    "zeroRecords": "Không tìm thấy",
                    "info": "Hiển thị _PAGE_ của tất cả _PAGES_ trang",
                    "infoEmpty": "Không có kết quả tìm kiếm",
                    "infoFiltered": "(Lọc _MAX_ trong tất cả kết quả)",
                    "search": "Tìm kiếm: ",
                    "paginate": {
                        "previous": "Trang trước",
                        "next": "Trang kế"
                    }
                }
            });
        });

    </script>
}

Views/Order/CancelOrder.cshtml
@{
    Layout = null;
    int id = ViewBag.Id;
}

<p class="">
    @ViewData["Mess"]
</p>

@*<a onclick="CancelOrder('@Url.Action("CancelOrderConfirmed", "Order", new { id = id}, Context.Request.Scheme)')"
   class="btn btn-danger text-white">Hủy</a>*@
<a asp-action="CancelOrderConfirmed" asp-route-id="@id"
   class="btn btn-danger text-white">Hủy</a>

Views/Order/CancelOrderConfirmed.cshtml
@{
    Layout = null;
}

<p class="text-sm m-0">
    @ViewData["Mess"]
</p>

Views/Order/DeleteOrderCancel.cshtml
@model IEnumerable<Sky.Models.Order>
@using System.Globalization

@{
    ViewData["Title"] = "Xóa đơn hàng đã hủy";
    Layout = "~/Areas/Identity/Pages/Admin/_AdminLayout.cshtml";
    int i = 0;
    CultureInfo culture = CultureInfo.CreateSpecificCulture("vi-VI");
}

<h2 class="text-center mt-5 mb-4">
    <i class="fas fa-times-circle text-danger fa-lg mr-2"></i>
    Đơn hàng đã hủy
</h2>

<div class="card shadow mb-3">
    <div class="card-body d-flex py-2">
        <div class="flex-grow-1 d-inline-flex form-inline">
            <div class="form-group m-2">
                <a class="btn btn-success" asp-action="Manage">Xem tất cả</a>
            </div>
            <div class="form-group m-2">
                <a class="btn btn-danger" asp-action="DeleteAllOrderCancel">Xóa tất cả</a>
            </div>
        </div>
        <div class="p-0">
            <form asp-action="AcceptOrder" method="get" class="form-inline ">
                <div class="form-group m-2">
                    <label class="input-group-prepend">Tìm kiếm </label>
                </div>
                <div class="form-group m-2">
                    <div class="input-group">
                        <input type="text" class="form-control" name="SearchString" value="@ViewData["CurrentFilter"]" />
                        <div class="input-group-append">
                            <button class="btn btn-primary" type="submit">
                                <i class="fas fa-search"></i>
                            </button>
                        </div>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>

<div class="card shadow">
    <div class="card-body">
        <div class="table-responsive">
            <table class="table dataTable" id="dataTable" width="100%" cellspacing="0">
                <thead>
                    <tr class="text-center">
                        <th>STT</th>
                        <th>
                            Mã đơn hàng
                        </th>
                        <th>

                        </th>
                        <th>
                            Tình trạng
                        </th>
                        <th>
                            Ngày đặt hàng
                        </th>
                        <th>
                            Tổng tiền
                        </th>
                        <th></th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var item in Model)
                    {
                        <tr class="text-center">
                            <td class="align-middle">
                                @(i+1)
                            </td>
                            <td class="align-middle">
                                <small>@Html.DisplayFor(modelItem => item.OrderTextId)</small>
                            </td>
                            <td class="align-middle">
                                @*<img src="@("~/image/" + ViewBag.ListImg[i])" asp-append-version="true" style="height:150px" class="rounded" />*@
                            </td>
                            <td class="align-middle">
                                @Html.DisplayFor(modelItem => item.OrderStatus)
                            </td>
                            <td class="align-middle">
                                @((item.OrderDate).ToString("dd/MM/yyyy HH:mm"))
                            </td>
                            <td class="align-middle">
                                <strong>@((item.OrderPrice).ToString("#,##0", culture))</strong>
                            </td>
                            <td class="align-middle">
                                <a onclick="showInPopup('@Url.Action("Edit", "Order", new { id = item.OrderId}, Context.Request.Scheme)', 'Edit Order')"
                                   class="btn btn-sm btn-primary text-white">Sửa</a>
                                <a onclick="showInPopup('@Url.Action("Details", "Order", new { id = item.OrderId}, Context.Request.Scheme)', 'Detail Order')"
                                   class="btn btn-sm btn-success text-white">Xem</a>
                                <a onclick="showInPopup('@Url.Action("Delete", "Order", new { id = item.OrderId}, Context.Request.Scheme)', 'Delete Order')"
                                   class="btn btn-sm btn-danger text-white">Xóa</a>
                                <a onclick="showInPopup('@Url.Action("ChiTiet", "OrderDetail", new { id = item.OrderId}, Context.Request.Scheme)', 'ChiTiet Order')"
                                   class="btn btn-sm btn-info text-white">Chi Tiết</a>
                                <a asp-action="DeleteOrderCancelConfirmed" asp-route-id="@item.OrderId"
                                   class="btn btn-sm btn-secondary text-white">Xóa</a>
                            </td>
                        </tr>
                        i++;
                    }
                </tbody>
            </table>
        </div>
    </div>
</div>



<div class="modal" tabindex="-1" role="dialog" id="form-modal">
    <div class="modal-dialog modal-lg" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title"></h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">×</span>
                </button>
            </div>
            <div class="modal-body">

            </div>
        </div>
    </div>
</div>


<p class="h4 my-5 text-center">
    @ViewData["Mess"]
</p>

@section Scripts{
    <script>
        $(document).ready(function () {
            $('#dataTable').DataTable({
                "language": {
                    "lengthMenu": "Hiển thị _MENU_ kết quả mỗi trang",
                    "zeroRecords": "Không tìm thấy",
                    "info": "Hiển thị _PAGE_ của tất cả _PAGES_ trang",
                    "infoEmpty": "Không có kết quả tìm kiếm",
                    "infoFiltered": "(Lọc _MAX_ trong tất cả kết quả)",
                    "search": "Tìm kiếm: ",
                    "paginate": {
                        "previous": "Trang trước",
                        "next": "Trang kế"
                    }
                }
            });
        });

    </script>
}