Models/ErrorViewModel.cs
using System;

namespace Sky.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Controllers/FavoriteDetailController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Sky.Areas.Identity.Data;
using Sky.Data;
using Sky.Models;
using static Sky.Data.Helper;

namespace Sky.Controllers
{
    public class FavoriteDetailController : Controller
    {
        private readonly SkyAppDbContext _context;
        private readonly UserManager<SkyUser> _userManager;
        private readonly SignInManager<SkyUser> _signInManager;

        public FavoriteDetailController(SkyAppDbContext context,
            UserManager<SkyUser> userManager,
            SignInManager<SkyUser> signInManager)
        {
            _context = context;
            _userManager = userManager;
            _signInManager = signInManager;
        }

        [NoDirectAccess]
        [Authorize]
        public async Task<IActionResult> Favorite_Partial()
        {
            var id = _userManager.GetUserId(User);

            var favo = _context.FavoriteDbSet.Where(c => c.UserId == id).ToList().FirstOrDefault();

            var skyAppDbContext = _context.FavoriteDetailDbSet.Include(c => c.Favorite).Include(c => c.Product).Where(c => c.FavoriteId == favo.FavoriteId);

            ViewData["More"] = "";

            if (!skyAppDbContext.Any())
            {
                ViewData["FavoriteCount"] = "Bạn chưa có sản phẩm trong yêu thích";
            }

            if (skyAppDbContext.Count() > 5)
            {
                ViewData["More"] = "...";
            }

            ViewData["FavoriteCount"] = "Yêu thích có " + skyAppDbContext.Count() + " sản phẩm";

            return View(await skyAppDbContext.Take(5).ToListAsync());
        }

        
        [NoDirectAccess]
        public async Task<IActionResult> AddtoFavo(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            try
            {
                if (!_signInManager.IsSignedIn(User))
                {
                    ViewData["Mess"] = "Bạn cần đăng nhập để tiếp tục";

                    return View();
                }

                var iduser = _userManager.GetUserId(User);

                var favo = _context.FavoriteDbSet.Where(c => c.UserId == iduser).ToList().FirstOrDefault();

                var check = _context.FavoriteDetailDbSet.Where(c => c.FavoriteId == favo.FavoriteId && c.ProductId == id).FirstOrDefault();

                if (check != null)
                {
                    ViewData["Mess"] = "Sản phẩm đã có trong danh sách yêu thích!";
                    return View();
                }

                var favode = new FavoriteDetail { FavoriteId = favo.FavoriteId, ProductId = (int)id };

                _context.FavoriteDetailDbSet.Add(favode);

                await _context.SaveChangesAsync();

                ViewData["Mess"] = "Thêm thành công";
            }
            catch
            {
                ViewData["Mess"] = "Thất bại";
            }
            return View();
        }


        [Authorize]
        [NoDirectAccess]
        public async Task<IActionResult> DeleteItemFavo(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            var iduser = _userManager.GetUserId(User);
            try
            {
                var favorite = _context.FavoriteDbSet.Where(c => c.UserId == iduser).ToList().FirstOrDefault();

                var favoritede = new FavoriteDetail { FavoriteId = favorite.FavoriteId, ProductId = (int)id };

                _context.FavoriteDetailDbSet.Remove(favoritede);

                await _context.SaveChangesAsync();

                ViewData["Mess"] = "Đã xóa";
            }
            catch
            {
                ViewData["Mess"] = "Thất bại";
            }
            return View();
            //KO return để ko hiển thị
        }


        [Authorize]
        // GET: FavoriteDetail
        public async Task<IActionResult> Index()
        {
            var id = _userManager.GetUserId(User);

            var favo = _context.FavoriteDbSet.Where(c => c.UserId == id).ToList().FirstOrDefault();

            var skyAppDbContext = _context.FavoriteDetailDbSet.Include(c => c.Favorite).Include(c => c.Product).Include(c => c.Product.Type).Include(c => c.Product.Category).Where(c => c.FavoriteId == favo.FavoriteId);

            return View(await skyAppDbContext.ToListAsync());
        }
    }
}

Controllers/ProductController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Sky.Areas.Identity.Data;
using Sky.Data;
using Sky.Models;
using static Sky.Data.Helper;

namespace Sky.Controllers
{
    public class ProductController : Controller
    {
        const int USER_PER_PAGE = 12;
        private readonly SkyAppDbContext _context;
        private readonly UserManager<SkyUser> _userManager;
        private readonly SignInManager<SkyUser> _signInManager;
        private readonly IWebHostEnvironment _hostEnvironment;

        public ProductController(SkyAppDbContext context,
            UserManager<SkyUser> userManager,
            SignInManager<SkyUser> signInManager,
            IWebHostEnvironment hostEnvironment)
        {
            _context = context;
            _userManager = userManager;
            _signInManager = signInManager;
            _hostEnvironment = hostEnvironment;
        }

        
        [NoDirectAccess]
        public async Task<IActionResult> AddtoCart(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            try
            {
                if (!_signInManager.IsSignedIn(User))
                {
                    ViewData["Mess"] = "Bạn cần đăng nhập để tiếp tục";

                    return View();
                }

                var iduser = _userManager.GetUserId(User);

                var cart = _context.CartDbSet.Where(c => c.UserId == iduser).ToList().FirstOrDefault();

                var check = _context.CartDetailDbSet.Where(c => c.CartId == cart.CartId && c.ProductId == id).FirstOrDefault();

                if (check != null)
                {
                    check.ProductQuantity += 1;

                    ViewData["Mess"] = "Đã cập nhật +1 !";
                }
                else
                {
                    var cartde = new CartDetail { CartId = cart.CartId, ProductId = (int)id, ProductQuantity = 1 };

                    _context.CartDetailDbSet.Add(cartde);

                    ViewData["Mess"] = "Thêm thành công";
                }

                await _context.SaveChangesAsync();


            }
            catch
            {
                ViewData["Mess"] = "Thất bại";
            }
            return View();
        }


        
        [NoDirectAccess]
        public async Task<IActionResult> AddtoCart2(string id, string quantity)
        {
            if (id == null || quantity == null)
            {
                return NotFound();
            }

            try
            {
                if (!_signInManager.IsSignedIn(User))
                {
                    ViewData["Mess"] = "Bạn cần đăng nhập để tiếp tục";

                    return View();
                }

                var iduser = _userManager.GetUserId(User);

                var cart = _context.CartDbSet.Where(c => c.UserId == iduser).ToList().FirstOrDefault();

                var check = _context.CartDetailDbSet.Where(c => c.CartId == cart.CartId && c.ProductId == Convert.ToInt32(id)).FirstOrDefault();

                if (check != null)
                {
                    check.ProductQuantity += Convert.ToInt32(quantity);

                    ViewData["Mess"] = "Đã cập nhật +" + quantity;

                    await _context.SaveChangesAsync();

                    return View();
                }
                else
                {
                    var cartde = new CartDetail { CartId = cart.CartId, ProductId = Convert.ToInt32(id), ProductQuantity = Convert.ToInt32(quantity) };

                    _context.CartDetailDbSet.Add(cartde);

                    ViewData["Mess"] = "Thành công";
                }
                await _context.SaveChangesAsync();
            }
            catch
            {
                ViewData["Mess"] = "Thất bại";
            }
            return View();
        }

        //-------------------------------------------------------------------------------------------------------------------------
        public async Task<IActionResult> SearchAsync(string q, string sortOrder, int PageNumber)
        {
            ViewData["CurrentFilter"] = q;
            ViewData["Sort"] = sortOrder;

            var skyAppDbContext = _context.ProductDbSet.Where(c => c.ProductName.Contains(q) || c.ProductDescription.Contains(q));

            

            if (!skyAppDbContext.Any())
            {
                ViewBag.Message = "Không tìm thấy từ khóa '" + q + "'";
            }


            switch (sortOrder)
            {
                case "price":
                    skyAppDbContext = skyAppDbContext.OrderByDescending(s => s.ProductPrice);
                    break;
                case "price_asc":
                    skyAppDbContext = skyAppDbContext.OrderBy(s => s.ProductPrice);
                    break;
                case "view":
                    skyAppDbContext = skyAppDbContext.OrderByDescending(s => s.ViewCount);
                    break;
                case "new":
                    skyAppDbContext = skyAppDbContext.OrderByDescending(s => s.ProductDate);
                    break;
                default:
                    skyAppDbContext = skyAppDbContext.OrderBy(s => s.Type.TypeName);
                    break;
            }

            if (PageNumber == 0)
            {
                PageNumber = 1;
            }


            ViewData["PageNumber"] = PageNumber;

            int totalProducts = await skyAppDbContext.CountAsync();

            ViewData["TotalPages"] = (int)Math.Ceiling((double)totalProducts / USER_PER_PAGE);

            skyAppDbContext = skyAppDbContext.Include(p => p.Category).Include(p => p.Type);

            return View(await skyAppDbContext.Skip(USER_PER_PAGE * ((int)ViewData["PageNumber"] - 1)).Take(USER_PER_PAGE).AsNoTracking().ToListAsync());
        }

        public async Task<IActionResult> Nam(string searchString, string sortOrder, string type, int PageNumber)
        {
            ViewData["CurrentFilter"] = searchString;
            ViewData["Type"] = type;
            ViewData["Sort"] = sortOrder;

            //Lấy danh sách các loại type
            ViewBag.ListType = _context.ProductDbSet.Where(p => p.Category.CategoryName == "Nam" && p.ProductStatus == true).Select(c => c.Type.TypeName).Distinct().ToList();


            var skyAppDbContext = _context.ProductDbSet.Where(p => p.Category.CategoryName == "Nam" && p.ProductStatus == true);

            if (!String.IsNullOrEmpty(searchString))
            {
                skyAppDbContext = skyAppDbContext.Where(s => s.ProductName.Contains(searchString) || s.ProductDescription.Contains(searchString));
            }

            if (!String.IsNullOrEmpty(type))
            {
                skyAppDbContext = skyAppDbContext.Where(s => s.Type.TypeName.Contains(type));
            }

            if (!skyAppDbContext.Any())
            {
                ViewBag.Message = "Không tìm thấy từ khóa '" + searchString + "'";
            }


            switch (sortOrder)
            {
                case "price":
                    skyAppDbContext = skyAppDbContext.OrderByDescending(s => s.ProductPrice);
                    break;
                case "price_asc":
                    skyAppDbContext = skyAppDbContext.OrderBy(s => s.ProductPrice);
                    break;
                case "view":
                    skyAppDbContext = skyAppDbContext.OrderByDescending(s => s.ViewCount);
                    break;
                case "new":
                    skyAppDbContext = skyAppDbContext.OrderByDescending(s => s.ProductDate);
                    break;
                default:
                    skyAppDbContext = skyAppDbContext.OrderBy(s => s.Type.TypeName);
                    break;
            }

            if (PageNumber == 0)
            {
                PageNumber = 1;
            }
            

            ViewData["PageNumber"] = PageNumber;

            int totalProducts = await skyAppDbContext.CountAsync();

            ViewData["TotalPages"] = (int)Math.Ceiling((double)totalProducts / USER_PER_PAGE);

            skyAppDbContext = skyAppDbContext.Include(p => p.Category).Include(p => p.Type);

            return View(await skyAppDbContext.Skip(USER_PER_PAGE * ((int)ViewData["PageNumber"] - 1)).Take(USER_PER_PAGE).AsNoTracking().ToListAsync());
        }

        public async Task<IActionResult> Nu(string searchString, string sortOrder, string type, int PageNumber)
        {
            ViewData["CurrentFilter"] = searchString;
            ViewData["Type"] = type;
            ViewData["Sort"] = sortOrder;

            //Lấy danh sách các loại type
            ViewBag.ListType = _context.ProductDbSet.Where(p => p.Category.CategoryName == "Nu" && p.ProductStatus == true).Select(c => c.Type.TypeName).Distinct().ToList();


            var skyAppDbContext = _context.ProductDbSet.Where(p => p.Category.CategoryName == "Nu" && p.ProductStatus == true);

            if (!String.IsNullOrEmpty(searchString))
            {
                skyAppDbContext = skyAppDbContext.Where(s => s.ProductName.Contains(searchString) || s.ProductDescription.Contains(searchString));
            }

            if (!String.IsNullOrEmpty(type))
            {
                skyAppDbContext = skyAppDbContext.Where(s => s.Type.TypeName.Contains(type));
            }

            if (!skyAppDbContext.Any())
            {
                ViewBag.Message = "Không tìm thấy từ khóa '" + searchString + "'";
            }


            switch (sortOrder)
            {
                case "price":
                    skyAppDbContext = skyAppDbContext.OrderByDescending(s => s.ProductPrice);

Views/Home/BestFavorite.cshtml
@model IEnumerable<Sky.Models.Product>
@using System.Globalization

@{
    CultureInfo culture = CultureInfo.CreateSpecificCulture("vi-VI");
    Layout = "~/Views/Shared/_Layout3.cshtml";
    //Layout = null;
}
<div class="container">
    <div class="swiper-container">
        <div class="swiper-wrapper">
            @foreach (var item in Model)
            {
                <div class="swiper-slide">
                    <div class="product-item d-block">
                        <div class="border d-block my-2 rounded-lg" style="height:100%">
                            <div class="product-thum w-auto overflow-hidden" style="height:70%">
                                <a asp-controller="Product" asp-action="ChiTiet" asp-route-id="@item.ProductId">
                                    <img src="@("~/image/"+item.ProductImage)" asp-append-version="true" class="img-fluid product-image rounded-top" alt="ProductImage"
                                         style="height:300px; width:300px" data-toggle="tooltip" data-placement="top" title="@Html.DisplayFor(modelItem => item.ProductName)">
                                </a>
                            </div>
                            <div class="product-info p-2" style="height:30%">
                                <div class="product-name text-center mt-2">
                                    <span class="h6 d-inline-block text-dark text-truncate" data-toggle="tooltip" style="max-width:200px"
                                          data-placement="top" title="@Html.DisplayFor(modelItem => item.ProductName)">
                                        @Html.DisplayFor(modelItem => item.ProductName)
                                    </span>
                                </div>
                                <div class="d-flex align-items-center">
                                    <div class="product-price flex-grow-1 p-0">
                                        @{
                                            if (item.PreviousPrice == 0)
                                            {
                                                <strong class="text-dark text-lg"> @(item.ProductPrice.ToString("#,##0", culture))</strong>
                                            }
                                            else
                                            {
                                                <strong class="text-danger text-lg"> @(item.ProductPrice.ToString("#,##0", culture))</strong>
                                                <del class="text-xs text-dark"> @(item.PreviousPrice.ToString("#,##0", culture))</del>
                                            }
                                        }
                                    </div>
                                </div>
                                <div class="my-2">
                                    <a id="aaa" onclick="addItem('@Url.Action("AddtoFavo", "FavoriteDetail", new { id = @item.ProductId}, Context.Request.Scheme)', 'Add to Favorite')"
                                       class="btn btn-circle btn-outline-danger icon-cart" style="font-size:20px"
                                       data-toggle="tooltip" data-placement="top" title="Thêm vào danh sách yêu thích">
                                        <i class="fas fa-heart icon-cart"></i>
                                    </a>
                                    <a onclick="addItem('@Url.Action("AddtoCart", "Product", new { id = @item.ProductId}, Context.Request.Scheme)', 'Add to cart')"
                                       class="btn btn-circle btn-outline-primary icon-cart" style="font-size:20px"
                                       data-toggle="tooltip" data-placement="top" title="Thêm vào giỏ hàng">
                                        <i class="fas fa-cart-plus"></i>
                                    </a>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            }
        </div>
        <!-- Add Pagination -->
        @*<div class="swiper-pagination"></div>*@
        <!-- Add Arrows -->

    </div>
</div>
<div class="swiper-button-next"></div>
<div class="swiper-button-prev"></div>

@section Scripts{
    <script>
        var swiper = new Swiper('.swiper-container', {
            slidesPerView: 2,
            spaceBetween: 5,
            freeMode: true,

            autoplay: {
                delay: 4000,
                disableOnInteraction: true,
            },

            pagination: {
                el: '.swiper-pagination',
                clickable: true,
            },
            navigation: {
                nextEl: '.swiper-button-next',
                prevEl: '.swiper-button-prev',
            },
            breakpoints: {
                640: {
                    slidesPerView: 2,
                    spaceBetween: 10,
                },
                768: {
                    slidesPerView: 3,
                    spaceBetween: 10,
                },
                1024: {
                    slidesPerView: 4,
                    spaceBetween: 10,
                },
            }
        });

    </script>
}

Views/Home/BestSale.cshtml
@model IEnumerable<Sky.Models.Product>
@using System.Globalization

@{
    CultureInfo culture = CultureInfo.CreateSpecificCulture("vi-VI");
    Layout = "~/Views/Shared/_Layout3.cshtml";
    //Layout = null;
}
<div class="container">
    <div class="swiper-container">
        <div class="swiper-wrapper">
            @foreach (var item in Model)
            {
                <div class="swiper-slide">
                    <div class="product-item d-block">
                        <div class="border d-block my-2 rounded-lg" style="height:100%">
                            <div class="product-thum w-auto overflow-hidden" style="height:70%">
                                <a asp-controller="Product" asp-action="ChiTiet" asp-route-id="@item.ProductId">
                                    <img src="@("~/image/"+item.ProductImage)" asp-append-version="true" class="img-fluid product-image rounded-top" alt="ProductImage"
                                         style="height:300px; width:300px" data-toggle="tooltip" data-placement="top" title="@Html.DisplayFor(modelItem => item.ProductName)">
                                </a>
                            </div>
                            <div class="product-info p-2" style="height:30%">
                                <div class="product-name text-center mt-2">
                                    <span class="h6 d-inline-block text-dark text-truncate" data-toggle="tooltip" style="max-width:200px"
                                          data-placement="top" title="@Html.DisplayFor(modelItem => item.ProductName)">
                                        @Html.DisplayFor(modelItem => item.ProductName)
                                    </span>
                                </div>
                                <div class="d-flex align-items-center">
                                    <div class="product-price flex-grow-1 p-0">
                                        @{
                                            if (item.PreviousPrice == 0)
                                            {
                                                <strong class="text-dark text-lg"> @(item.ProductPrice.ToString("#,##0", culture))</strong>
                                            }
                                            else
                                            {
                                                <strong class="text-danger text-lg"> @(item.ProductPrice.ToString("#,##0", culture))</strong>
                                                <del class="text-xs text-dark"> @(item.PreviousPrice.ToString("#,##0", culture))</del>
                                            }
                                        }
                                    </div>
                                </div>
                                <div class="my-2">
                                    <a id="aaa" onclick="addItem('@Url.Action("AddtoFavo", "FavoriteDetail", new { id = @item.ProductId}, Context.Request.Scheme)', 'Add to Favorite')"
                                       class="btn btn-circle btn-outline-danger icon-cart" style="font-size:20px"
                                       data-toggle="tooltip" data-placement="top" title="Thêm vào danh sách yêu thích">
                                        <i class="fas fa-heart icon-cart"></i>
                                    </a>
                                    <a onclick="addItem('@Url.Action("AddtoCart", "Product", new { id = @item.ProductId}, Context.Request.Scheme)', 'Add to cart')"
                                       class="btn btn-circle btn-outline-primary icon-cart" style="font-size:20px"
                                       data-toggle="tooltip" data-placement="top" title="Thêm vào giỏ hàng">
                                        <i class="fas fa-cart-plus"></i>
                                    </a>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            }
        </div>
        <!-- Add Pagination -->
        @*<div class="swiper-pagination"></div>*@
        <!-- Add Arrows -->

    </div>
</div>
<div class="swiper-button-next"></div>
<div class="swiper-button-prev"></div>

@section Scripts{
    <script>
        var swiper = new Swiper('.swiper-container', {
            slidesPerView: 2,
            spaceBetween: 5,
            freeMode: true,

            autoplay: {
                delay: 4000,
                disableOnInteraction: true,
            },

            pagination: {
                el: '.swiper-pagination',
                clickable: true,
            },
            navigation: {
                nextEl: '.swiper-button-next',
                prevEl: '.swiper-button-prev',
            },
            breakpoints: {
                640: {
                    slidesPerView: 2,
                    spaceBetween: 10,
                },
                768: {
                    slidesPerView: 3,
                    spaceBetween: 10,
                },
                1024: {
                    slidesPerView: 4,
                    spaceBetween: 10,
                },
            }
        });

    </script>
}

Views/Home/BestView.cshtml
@model IEnumerable<Sky.Models.Product>
@using System.Globalization

@{
    CultureInfo culture = CultureInfo.CreateSpecificCulture("vi-VI");
    Layout = "~/Views/Shared/_Layout3.cshtml";
    //Layout = null;
}
<div class="container">
    <div class="swiper-container">
        <div class="swiper-wrapper">
            @foreach (var item in Model)
            {
                <div class="swiper-slide">
                    <div class="product-item d-block">
                        <div class="border d-block my-2 rounded-lg" style="height:100%">
                            <div class="product-thum w-auto overflow-hidden" style="height:70%">
                                <a asp-controller="Product" asp-action="ChiTiet" asp-route-id="@item.ProductId">
                                    <img src="@("~/image/"+item.ProductImage)" asp-append-version="true" class="img-fluid product-image rounded-top" alt="ProductImage"
                                         style="height:300px; width:300px" data-toggle="tooltip" data-placement="top" title="@Html.DisplayFor(modelItem => item.ProductName)">
                                </a>
                            </div>
                            <div class="product-info p-2" style="height:30%">
                                <div class="product-name text-center mt-2">
                                    <span class="h6 d-inline-block text-dark text-truncate" data-toggle="tooltip" style="max-width:200px"
                                        data-placement="top" title="@Html.DisplayFor(modelItem => item.ProductName)">
                                        @Html.DisplayFor(modelItem => item.ProductName)
                                    </span>
                                </div>
                                <div class="d-flex align-items-center">
                                    <div class="product-price flex-grow-1 p-0">
                                        @{
                                            if (item.PreviousPrice == 0)
                                            {
                                                <strong class="text-dark text-lg"> @(item.ProductPrice.ToString("#,##0", culture))</strong>
                                            }
                                            else
                                            {
                                                <strong class="text-danger text-lg"> @(item.ProductPrice.ToString("#,##0", culture))</strong>
                                                <del class="text-xs text-dark"> @(item.PreviousPrice.ToString("#,##0", culture))</del>
                                            }
                                        }
                                    </div>
                                </div>
                                <div class="my-2">
                                    <a id="aaa" onclick="addItem('@Url.Action("AddtoFavo", "FavoriteDetail", new { id = @item.ProductId}, Context.Request.Scheme)', 'Add to Favorite')"
                                       class="btn btn-circle btn-outline-danger icon-cart" style="font-size:20px"
                                       data-toggle="tooltip" data-placement="top" title="Thêm vào danh sách yêu thích">
                                        <i class="fas fa-heart icon-cart"></i>
                                    </a>
                                    <a onclick="addItem('@Url.Action("AddtoCart", "Product", new { id = @item.ProductId}, Context.Request.Scheme)', 'Add to cart')"
                                       class="btn btn-circle btn-outline-primary icon-cart" style="font-size:20px"
                                       data-toggle="tooltip" data-placement="top" title="Thêm vào giỏ hàng">
                                        <i class="fas fa-cart-plus"></i>
                                    </a>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            }
        </div>
        <!-- Add Pagination -->
        @*<div class="swiper-pagination"></div>*@
        <!-- Add Arrows -->

    </div>
</div>
<div class="swiper-button-next"></div>
<div class="swiper-button-prev"></div>

@section Scripts{
    <script>
        var swiper = new Swiper('.swiper-container', {
            slidesPerView: 2,
            spaceBetween: 5,
            freeMode: true,

            autoplay: {
                delay: 4000,
                disableOnInteraction: true,
            },

            pagination: {
                el: '.swiper-pagination',
                clickable: true,
            },
            navigation: {
                nextEl: '.swiper-button-next',
                prevEl: '.swiper-button-prev',
            },
            breakpoints: {
                640: {
                    slidesPerView: 2,
                    spaceBetween: 10,
                },
                768: {
                    slidesPerView: 3,
                    spaceBetween: 10,
                },
                1024: {
                    slidesPerView: 4,
                    spaceBetween: 10,
                },
            }
        });

    </script>
}

Views/Home/Errors.cshtml
@{ 
    Layout = "~/Views/Shared/_Layout.cshtml";
    ViewData["Title"] = "Error";
}


<div class="container-fluid">

    <!-- 404 Error Text -->
    <div class="text-center mt-5">
        <div class="error mx-auto" data-text="404">404</div>
        <p class="lead text-gray-800 mb-5">Page Not Found</p>
        <p class="text-gray-500 mb-0">It looks like you found a glitch in the matrix...</p>
        <a asp-action="Index" class="btn btn-primary mt-5">← Back to Home</a>
    </div>

</div>

Views/Home/Menu.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
    Layout = null;
}


@foreach (var item in ViewBag.menu)
{
    <li class="nav-item">
        <a class="dropdown-item py-2 text-dark" asp-route-cate="@item" asp-controller="Product" asp-action="Category">@item</a>
    </li>
}