Areas/Identity/Pages/Admin/Role/Delete.cshtml.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace Sky.Areas.Identity.Pages.Role
{
    [Authorize(Roles = "Manager")]
    public class DeleteModel : PageModel
    {
        private readonly RoleManager<IdentityRole> _roleManager;

        public DeleteModel(RoleManager<IdentityRole> roleManager)
        {
            _roleManager = roleManager;
        }

        public class InputModel
        {
            [Required]
            public string ID { set; get; }
            public string Name { set; get; }

        }

        [BindProperty]
        public InputModel Input { set; get; }

        [BindProperty]
        public bool IsConfirmed { set; get; }

        [TempData] // Sử dụng Session
        public string StatusMessage { get; set; }

        public IActionResult OnGet() => NotFound("Không thấy");

        public async Task<IActionResult> OnPost()
        {

            if (!ModelState.IsValid)
            {
                return NotFound("Không xóa được");
            }

            var role = await _roleManager.FindByIdAsync(Input.ID);
            if (role == null)
            {
                return NotFound("Không thấy role cần xóa");
            }

            ModelState.Clear();

            if (IsConfirmed)
            {
                //Xóa
                await _roleManager.DeleteAsync(role);
                StatusMessage = "Đã xóa " + role.Name;

                return RedirectToPage("Index");
            }
            else
            {
                Input.Name = role.Name;
                IsConfirmed = true;

            }

            return Page();
        }
    }
}

Controllers/TypeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Sky.Data;
using Sky.Models;
using static Sky.Data.Helper;
using Type = Sky.Models.Type;

namespace Sky.Controllers
{
    [Authorize(Roles = "Admin, Manager")]
    public class TypeController : Controller
    {
        private readonly SkyAppDbContext _context;

        public TypeController(SkyAppDbContext context)
        {
            _context = context;
        }

        
        // GET: Type
        public async Task<IActionResult> Index()
        {
            return View(await _context.TypeDbSet.ToListAsync());
        }

        [NoDirectAccess]
        // GET: Type/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var @type = await _context.TypeDbSet
                .FirstOrDefaultAsync(m => m.TypeId == id);
            if (@type == null)
            {
                return NotFound();
            }

            return View(@type);
        }

        [NoDirectAccess]
        // GET: Type/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Type/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.

        [NoDirectAccess]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("TypeId,TypeName")] Type @type)
        {
            if (ModelState.IsValid)
            {
                _context.Add(@type);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(@type);
        }

        [NoDirectAccess]
        // GET: Type/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var @type = await _context.TypeDbSet.FindAsync(id);
            if (@type == null)
            {
                return NotFound();
            }
            return View(@type);
        }

        [NoDirectAccess]
        // POST: Type/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("TypeId,TypeName")] Type @type)
        {
            if (id != @type.TypeId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(@type);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!TypeExists(@type.TypeId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(@type);
        }

        [NoDirectAccess]
        // GET: Type/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var @type = await _context.TypeDbSet
                .FirstOrDefaultAsync(m => m.TypeId == id);
            if (@type == null)
            {
                return NotFound();
            }

            return View(@type);
        }

        [NoDirectAccess]
        // POST: Type/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var @type = await _context.TypeDbSet.FindAsync(id);
            _context.TypeDbSet.Remove(@type);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool TypeExists(int id)
        {
            return _context.TypeDbSet.Any(e => e.TypeId == id);
        }
    }
}

Views/Type/Create.cshtml
@model Sky.Models.Type

@{
    ViewData["Title"] = "Create";
    Layout = "~/Views/Shared/_Layout2.cshtml";
}


<div class="row">
    <div class="col-md-10">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label class="control-label">Tên loại sản phẩm</label>
                <input asp-for="TypeName" class="form-control" />
                <span asp-validation-for="TypeName" class="text-danger"></span>
            </div>
            <hr />
            <div class="form-group">
                <input type="submit" value="Lưu lại" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>


@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/Type/Delete.cshtml
@model Sky.Models.Type

@{
    ViewData["Title"] = "Delete";
    Layout = "~/Views/Shared/_Layout2.cshtml";
}

<h4>Bạn có chắc chắn muốn xóa loại sản phẩm "@Model.TypeName" không?</h4>
<div>
    <hr />
    <form asp-action="Delete">
        <input type="hidden" asp-for="TypeId" />
        <input type="submit" value="Xóa" class="btn btn-danger" />
    </form>
</div>

Views/Type/Details.cshtml
@model Sky.Models.Type

@{
    ViewData["Title"] = "Details";
    Layout = "~/Views/Shared/_Layout2.cshtml";
}

<h1>Details</h1>

<div>
    <h4>Type</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.TypeName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.TypeName)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.TypeId">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

Views/Type/Edit.cshtml
@model Sky.Models.Type

@{
    ViewData["Title"] = "Edit";
    Layout = "~/Views/Shared/_Layout2.cshtml";
}


<div class="row">
    <div class="col-md-10">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="TypeId" />
            <div class="form-group">
                <label class="control-label">Tên loại sản phẩm</label>
                <input asp-for="TypeName" class="form-control" />
                <span asp-validation-for="TypeName" class="text-danger"></span>
            </div>
            <hr />
            <div class="form-group">
                <input type="submit" value="Lưu" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/Type/Index.cshtml
@model IEnumerable<Sky.Models.Type>

@{
    ViewData["Title"] = "Quản lí loại sản phẩm";
    Layout = "~/Areas/Identity/Pages/Admin/_AdminLayout.cshtml";
    int i = 0;
}


<div class="card shadow mt-5">
    <div class="card-header py-3 d-flex align-items-center">
        <div class="flex-grow-1">
            <h4 class="m-0 font-weight-bold text-primary">Quản lí danh mục sản phẩm</h4>
        </div>
        <div>
            <a onclick="showInPopup('@Url.Action("Create","Type", null, Context.Request.Scheme)', 'Tạo loại sản phẩm mới')" class="btn btn-primary text-white px-3">
                Tạo mới <i class="fas fa-plus ml-2"></i>
            </a>
        </div>
    </div>
    <div class="card-body">
        <table class="table table-bordered">
            <thead>
                <tr>
                    <th>STT</th>
                    <th>
                        Tên loại sản phẩm
                    </th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model)
                {
                    <tr>
                        <td class="align-middle">@(i+1)</td>
                        <td class="align-middle">
                            @Html.DisplayFor(modelItem => item.TypeName)
                        </td>
                        <td class="align-middle">
                            <a onclick="showInPopup('@Url.Action("Edit","Type", new { id = item.TypeId}, Context.Request.Scheme)', 'Sửa danh mục')" class="btn btn-sm btn-success text-white">Sửa</a>
                            <a onclick="showInPopup('@Url.Action("Delete","Type", new { id = item.TypeId}, Context.Request.Scheme)', 'Xóa danh mục')" class="btn btn-sm btn-danger text-white">Xóa</a>
                        </td>
                    </tr>
                    i++;
                }
            </tbody>
        </table>

    </div>
</div>

<div class="modal" tabindex="-1" role="dialog" id="form-modal">
    <div class="modal-dialog modal-lg" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title"></h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">×</span>
                </button>
            </div>
            <div class="modal-body">

            </div>
        </div>
    </div>
</div>